name: Windows
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Stop Converting to CRLF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build --config Release
    - name: Test
      run: ctest --test-dir build -C Release --output-on-failure
